_target_: src.trainers.probe_trainer.ProbeTrainer

# --- Training Hyperparameters ---
learning_rate: 0.001 # Standard name
batch_size: 32     # Standard name
num_epochs: 10     # Standard name

# Optional DataLoader parameters (using standard names)
num_workers: 4
pin_memory: True 