_target_: src.trainers.sae_trainer.SAETrainer

# --- Training Hyperparameters ---
learning_rate: 1e-4 # Standard name (Updated)
batch_size: 16     # Standard name
num_epochs: 20     # Standard name
l1: 1e-5           # SAE-specific parameter

# Optional DataLoader parameters (using standard names)
num_workers: 4
pin_memory: True 