# config/training/probe_training.yaml
# Hyperparameters for Linear Probe training

batch_size: 32
num_epochs: 10
learning_rate: 0.001

# Optional: DataLoader related parameters
num_workers: 4
pin_memory: True 