# config/training/sae_training.yaml
# Hyperparameters for Sparse Autoencoder training

batch_size: 4
num_epochs: 20
lr: 1e-4
l1: 1e-5 # L1 regularization strength

# Optional: DataLoader related parameters
num_workers: 4
pin_memory: True 