_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-x86_64
batch_size:
    value: 64
hidden_size:
    value: 73728
input_size:
    value: 589824
l1_lambda:
    value: 1e-05
learning_rate:
    value: 0.001
num_epochs:
    value: 20
